                set(enter_gui_button,'Visible','OFF')
                                set(gas_mains_question,'Visible','Off') 
                set(button_yes_gas_mains,'Visible','Off') 
                set(button_no_gas_mains,'Visible','Off') 
                                set(pool_question,'Visible','Off') 
                set(button_yes_pool,'Visible','Off') 
                set(button_no_pool,'Visible','Off') 
                                set(percentage_question,'Visible','Off')
                set(percentage_popupmenu,'Visible','Off')  
                set(percentage_next_button,'Visible','Off')   
                                set(performance_question,'Visible','Off')
                set(performance_popupmenu,'Visible','Off')  
                set(performance_next_button,'Visible','Off')  
                                set(text_solar_question,'Visible','OFF') 
                set(button_yes_solar,'Visible','OFF') 
                set(button_no_solar,'Visible','OFF')
                                set(solar_size_next_button,'Visible','off') 
                set(KW_popupmenu,'Visible','off')                
                set(solar_size_question,'Visible','off')
                set(text_solar_question,'Visible','OFF') 
                set(button_yes_solar,'Visible','OFF') 
                set(button_no_solar,'Visible','OFF')       
      
                
                set(cost_solar_question,'Visible','OFF') 
                set(cost_popupmenu,'Visible','OFF')                
                set(cost_next_button,'Visible','OFF')  
                                set(text_battery_question,'Visible','OFF') 
                set(button_yes_battery,'Visible','OFF') 
                set(button_no_battery,'Visible','OFF')
                                set(battery_size_question,'Visible','OFF') 
                set(KWHR_popupmenu,'Visible','OFF') 
                set(battery_size_next_button,'Visible','OFF')
                                set(text_battery_question,'Visible','OFF') 
                set(button_yes_battery,'Visible','OFF') 
                set(button_no_battery,'Visible','OFF')
                                   
                set(cost_battery_question,'Visible','Off') 
                set(battery_cost_popupmenu,'Visible','Off')         
                set(battery_cost_next_button,'Visible','Off') 
                                set(text_roof_question,'Visible','OFF') 
                set(tilt_popupmenu,'Visible','OFF')  
                set(roof_next_button,'Visible','OFF')  
                                set(orientation_next_button,'Visible','Off')         
                set(orientation_edit_display,'Visible','Off') 
                set(text_orientation_question,'Visible','Off')  
                set(compass_image,'Visible','Off')                 

                set(radio_north_button,'Visible','Off');                set(radio_north_west_button,'Visible','Off')    
                set(radio_east_button,'Visible','Off');                 set(radio_north_east_button,'Visible','Off')  
                set(radio_south_button,'Visible','Off');                set(radio_south_east_button,'Visible','Off')  
                set(radio_west_button,'Visible','Off');                 set(radio_south_west_button,'Visible','Off') 
                                set(state_display_button,'Visible','Off')         
                set(state_next_button,'Visible','Off') 
                set(text_state_question,'Visible','Off')  
                set(postcode_edit,'Visible','Off')      
                 set(text_state_codes,'Visible','Off');
                                  set(post_code_table,'Visible','Off')
                                                  set(text_bill_question,'Visible','Off')         
                set(bill_edit,'Visible','Off') 
                set(bill_next_button,'Visible','Off')
                set(bill_skip_button,'Visible','Off')  
                                set(number_people_question,'Visible','Off')  
                set(people_popupmenu,'Visible','Off') 
                set(people_next_button,'Visible','Off') 